
###
## nuevo Incorrecto
POST http://localhost:8090/auth/nuevo HTTP/1.1
Content-Type:application/json

{
    "nickname" : "prueba",
    "email" : "@",
    "password": "a",
    "roles" : ["admin"]
}

###
## nuevo ok
POST http://localhost:8090/auth/nuevo HTTP/1.1
Content-Type:application/json

{
    "nombre" : "Pablo Cerda",
    "nickname" : "uarret",
    "email" : "uarret@gmail.com",
    "password": "Notelodigo@1"
}

###
## login ok
POST http://localhost:8090/auth/login HTTP/1.1
Content-Type:application/json

{
    "nickname" : "uarret",
    "password": "Notelodigo@1"
}

###
## getUserByNick
GET http://localhost:8090/api/v1/usuario/pablox HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwYWJsb3giLCJpYXQiOjE3MDc5MzAwOTgsImV4cCI6MTcwNzk2NjA5OH0._xnTenxbEoNWilcGANzdgUahBf1YgeIqsjz0etYSxjY

###
## getAllUser
GET http://localhost:8090/api/v1/usuarios HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjb2xpam8iLCJpYXQiOjE3MDc0NzI4NTMsImV4cCI6MTcwNzUwODg1M30.bXoiltBf6swCYNwLGaphcL8Yu6_6sduBBL5NFfn84jg

###
## numeroAleatorio 1 al 6
GET http://localhost:8090/api/v1/game/aleatorio HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjb2xpam8iLCJpYXQiOjE3MDc0NzI4NTMsImV4cCI6MTcwNzUwODg1M30.bXoiltBf6swCYNwLGaphcL8Yu6_6sduBBL5NFfn84jg

###
## UPDATE user
PUT http://localhost:8090/api/v1/usuario/update/alexgarc HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjb2xpam8iLCJpYXQiOjE3MDc0NzI4NTMsImV4cCI6MTcwNzUwODg1M30.bXoiltBf6swCYNwLGaphcL8Yu6_6sduBBL5NFfn84jg

{
    "nickname" : "alexgar",
    "nombre" : "alexete",
    "email" : "alex@cambio.es"
}
###
## DELETE user
DELETE http://localhost:8090/api/v1/usuario/borrar/alexgar HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjb2xpam8iLCJpYXQiOjE3MDc0NzI4NTMsImV4cCI6MTcwNzUwODg1M30.bXoiltBf6swCYNwLGaphcL8Yu6_6sduBBL5NFfn84jg


###
## Nuevo Game
POST http://localhost:8090/partida/crear HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwYWJsb3giLCJpYXQiOjE3MDc5ODM4OTIsImV4cCI6MTcwODAxOTg5Mn0.LuiP5O8hRmyVW-wDvgpuz715WDuHXOR7VprR-iAJXBw

###
## Partida add jugador
POST http://localhost:8090/jugador/addplayer HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwYWJsb3giLCJpYXQiOjE3MDc5ODM4OTIsImV4cCI6MTcwODAxOTg5Mn0.LuiP5O8hRmyVW-wDvgpuz715WDuHXOR7VprR-iAJXBw

{
    "idUser" : 2,
    "idPartida" : 1,
    "colorFicha" : "default"
}

###
## Contar id partida
GET http://localhost:8090/jugador/empezar/1 HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwYWJsb3giLCJpYXQiOjE3MDc5ODM4OTIsImV4cCI6MTcwODAxOTg5Mn0.LuiP5O8hRmyVW-wDvgpuz715WDuHXOR7VprR-iAJXBw