
###
## nuevo Incorrecto
POST http://localhost:8090/auth/nuevo HTTP/1.1
Content-Type:application/json

{
    "nickname" : "prueba",
    "email" : "@",
    "password": "a",
    "roles" : ["admin"]
}

###
## nuevo ok
POST http://localhost:8090/auth/nuevo HTTP/1.1
Content-Type:application/json

{
    "nombre" : "Alex Garcia",
    "nickname" : "alex",
    "email" : "alex@gmail.com",
    "password": "Notelodigo@1"
}

###
## login ok
POST http://localhost:8090/auth/login HTTP/1.1
Content-Type:application/json

{
    "nickname" : "alex",
    "password": "Notelodigo@1"
}

###
## getUserByNick
GET http://localhost:8090/api/v1/usuario/pablox HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwYWJsb3giLCJpYXQiOjE3MDc5MzAwOTgsImV4cCI6MTcwNzk2NjA5OH0._xnTenxbEoNWilcGANzdgUahBf1YgeIqsjz0etYSxjY

###
## getAllUser
GET http://localhost:8090/api/v1/usuarios HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjb2xpam8iLCJpYXQiOjE3MDc0NzI4NTMsImV4cCI6MTcwNzUwODg1M30.bXoiltBf6swCYNwLGaphcL8Yu6_6sduBBL5NFfn84jg

###
## numeroAleatorio 1 al 6
GET http://localhost:8090/api/v1/game/aleatorio HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjb2xpam8iLCJpYXQiOjE3MDc0NzI4NTMsImV4cCI6MTcwNzUwODg1M30.bXoiltBf6swCYNwLGaphcL8Yu6_6sduBBL5NFfn84jg

###
## UPDATE user
PUT http://localhost:8090/api/v1/usuario/update/alexgarc HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjb2xpam8iLCJpYXQiOjE3MDc0NzI4NTMsImV4cCI6MTcwNzUwODg1M30.bXoiltBf6swCYNwLGaphcL8Yu6_6sduBBL5NFfn84jg

{
    "nickname" : "alexgar",
    "nombre" : "alexete",
    "email" : "alex@cambio.es"
}
###
## DELETE user
DELETE http://localhost:8090/api/v1/usuario/borrar/alexgar HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjb2xpam8iLCJpYXQiOjE3MDc0NzI4NTMsImV4cCI6MTcwNzUwODg1M30.bXoiltBf6swCYNwLGaphcL8Yu6_6sduBBL5NFfn84jg


###
## Nuevo Game
POST http://localhost:8090/partida/crear HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGV4IiwiaWF0IjoxNzA4NDQ1MzA2LCJleHAiOjE3MDg0ODEzMDZ9.PQj2TFfI5hn9DMiYl1BaWlKZx8vbR0Mqtv2n-zXjjFI

###
## Partida add jugador
POST http://localhost:8090/jugador/addplayer HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGV4IiwiaWF0IjoxNzA4NDI4NDk3LCJleHAiOjE3MDg0NjQ0OTd9.BzCbyH37FpQaRVUsuF9io1wtwxdIHiprWqt6ueagk0w

{
    "idUser" : 2,
    "idPartida" : 3,
    "colorFicha" : "default"
}

###
## Contar id partida
GET http://localhost:8090/jugador/empezar/1 HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGV4IiwiaWF0IjoxNzA4MDc4Mjk2LCJleHAiOjE3MDgxMTQyOTZ9.RVgFzoNKgHriywGMKBrxhR0hL-YMaTNx_756QCowDM4

###
## Mostrar lista partidas paginadas que no pertenece el usuario
GET http://localhost:8090/partida/lista/1 HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGV4IiwiaWF0IjoxNzA4MDc0ODEwLCJleHAiOjE3MDgxMTA4MTB9.-AeOy2uDVf7wP_p0mhwqGsMpIwK928b2ZmLWVWAKVH8

###
## Avanzar posiciones
POST http://localhost:8090/jugador/avanzar/1/1/2 HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGV4IiwiaWF0IjoxNzA4MzMzNDgwLCJleHAiOjE3MDgzNjk0ODB9.y4asV0pZSaWttJxT56zNhmVxitJzDuyahliAp6GNv7c

###
## Comprar propiedad
POST http://localhost:8090/propiedad/comprar/2/3/4/morada HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGV4IiwiaWF0IjoxNzA4NDI4NDk3LCJleHAiOjE3MDg0NjQ0OTd9.BzCbyH37FpQaRVUsuF9io1wtwxdIHiprWqt6ueagk0w